doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        use_savepoints: true

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        controller_resolver:
            auto_mapping: false
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Domain:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Entity'
                prefix: 'Domain\Entity'
                alias: Domain
            Computer:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Computer/Entity'
                prefix: 'Computer\Entity'
                alias: Domain
            Multiplayer:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Multiplayer/Entity'
                prefix: 'Multiplayer\Entity'
                alias: Domain