services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tests\Common\Fixtures:
        public: true

    Tests\Common\TestFileHelper:
        public: true

    Multiplayer\Service\SecretGenerator:
        public: true

    Multiplayer\MultiplayerFacade:
        public: true

    Elastic\ElasticClientFactory:
        public: true

    Elastic\ElasticMailerHandler:
        public: true

    Security\Service\UserCountryService:
        public: true

    Tests\Common\FixedClock:
        public: true

    Shared\Clock\Clock: '@Tests\Common\FixedClock'
